### PR TITLE
Change mechanism for default blog

### PR DESCRIPTION
**Pull request by ashleyblackmore**
This allows people to define their own DEFAULT_BLOGS in a settings file, and takes the data "bbolli" out of the code.

### CODE REVIEW

**Comment by bbolli** [comment]
Ping?

**Comment by ashleyblackmore** [comment]
Hey, been a touch busy this week. Thanks for responding, I'll fix up the PR

**Comment by ashleyblackmore** [comment]
Okay, updated. Let me know if you need anything else

**Comment by ashleyblackmore** [comment]
@bbolli this is ready to go :)

**Pull request closed without merging**
